# -*- coding: utf-8 -*-
"""Day1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1olqD6B_VR-IkKS2fa5coXOSs9OjoNe-y
"""



"""# “A person grows up when he’s able to overcome hardships. Protection is important, but there are some things that a person must learn on his own.” – Jiraiya"""

print('Hello world!')

# write your code below this line
print('Day 1 - Python print function')
print('The above is the print function')
print("Print('what is to be printed')")

print('ML Naruto')
print('I love my subscribers')
print('Please subscribe')

print("have u had ur lunch ?")

print("what's your name?")

print("This is my "I phone"")

print('This is my "I phone"')

# single quotes --> when the string is already has double quotes
# double quotes --> when the string is already has single quotes

print( ""+" sign is used for addition purpose")

print('"+" sign is used for addition purpose')

print('print("hey" + "ML Naruto")')

# string manipulation 

#first method
print("Hey naruto")
print("Hey naruto")
print("Hey naruto")
print("Hey naruto")
print("Hey naruto")

print("Hey naruto\nHey naruto\nHey naruto\nHey naruto\nHey naruto")  #second method

print("Hey naruto\n"*5) #third method

print("ML Naruto ")

print("ML"+" "+"Naruto")

print("hey"+" "+"subscribe"+" "+"to"+" "+"my"+" "+"channel")

# Debugging
# desired output --> Hey my name's ML Naruto 
print('Hey my name's ML Naruto')

# output --> hi python! Let me gain something!
print('hi python! Let me gain something!)

#output --> "*" is used for multiplication
print(""*" is used for multiplication")

# kdjfk;ldjfdjfjdf;'dfdfdfd\
# jdflk;jd;lkfjd;lfjdjdjdd;j'd
# dklfjd;jfdfd
# dl;kfjd;fjdk;''d;'fd
# dkfjdkfjdjf;djf;d'fkdlfkds
# kdjfl;kdj;'dsj';g'

# ctrl + / --> windows
# command + / --> mac

#Len function
print(len("You are beautiful"))

print(len("kdjflk;djfkdj;fjkd;fkj;ldkf;ldkflkd;lfkdlkfldkfdkl'fld'lfkd'lfkl'dkfdkfdk;'d"))

# input()
#if i want to allow my user to give the input , then i use input()
name = input("What is your good name ?")  #here name is the variable 
print(name)

roll_number = input("What is your roll number ?") #roll_number is our variable 
print(roll_number)

school = input("What is the name of your school: ")
length = len(school)
print(length)

a = input("a: ")
b = input("b: ")


c = b
b = a
a = c

print("a: "+a)
print("b: "+b)

# final project
print("Welcome to our NINJA restaurant")
food_items = input("What do you want to order sir ? ")
dessert_items = input("would you like to have any juice or a drink sir ? ")
print("These are "+food_items+","+dessert_items+ " items, you have ordered sir.")
print("Thank You! Visit again.")

